#
# Run cppcheck, build everything with debug features enabled, run tests.
# 

dist: trusty
language: cpp  

os: linux

compiler:
  - gcc
  - clang

addons:
  apt:
    packages: 
      - cmake 
      - clang-3.7 
      - gcc-5 
      - g++-5
      - cppcheck

      - libboost-dev
      - libboost-filesystem-dev
      - libx11-dev
      - libxrandr-dev
      - libxrender-dev
      - libx11-xcb-dev
      - libxcb-image0-dev
      - flac
      - libvorbis-dev
      - libfreetype6-dev          
    sources: ['kalakris-cmake', 'llvm-toolchain-precise', 'ubuntu-toolchain-r-test']
    
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then echo "linux stuff"; fi
    # - if [ $TRAVIS_OS_NAME == osx ]; then echo "osx stuff"; fi

before_script:
  - mkdir -p dist/debug
  - cd dist/debug
  - cmake -DCMAKE_BUILD_TYPE=Release ../..
  - cd ../..

script: 
  - ./cppcheck.sh &> check-results ; if [ -s check-results ]; then (cat check-results ; exit 1); else exit 0; fi
  - cd dist/debug ; make solemnsky_{tests,client,server}
  - ./tests/solemnsky_tests

