#
# Run cppcheck, build everything with debug features enabled, run tests.
# 

dist: trusty
language: cpp  

os:
  - linux
  - osx

compiler:
  - gcc
  - clang
    
before_install:
  - echo $LANG
  - echo $CC
  - echo $TRAVIS_OS_NAME
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install cmake boost; fi

before_script:
  - mkdir -p dist/debug
  - cd dist/debug
  - cmake -DCMAKE_BUILD_TYPE=Release ../..
  - cd ../..

script: 
  - ./cppcheck.sh &> check-results ; if [ -s check-results ]; then (cat check-results ; exit 1); else exit 0; fi
  - cd dist/debug ; make solemnsky_{tests,client,server}
  - ./tests/solemnsky_tests

