#
# Builds the nix expression for solemnsky, with server, client, and tests. Runs the tests.
# 

sudo: required
dist: trusty

install: 
  - bash <(curl -sS https://nixos.org/nix/install)
  - source $HOME/.nix-profile/etc/profile.d/nix.sh
  - nix-env -iA nixpkgs.p7zip nixpkgs.cppcheck
  - nix-build . -A deps

script:
  - nix-build . -A default && mkdir -p dist/release/ ; cd dist/release/ ; ../../result/bin/solemnsky_tests && cd ../../ ; ./cppcheck.sh &> check-results ; if [ -s check-results ]; then (cat check-results ; exit 1); else exit 0; fi

